export const SECTIONS = {
  education: {
    collection: 'education',
    label: 'Education',
    singular: 'Education Entry',
    orderField: 'start',
    orderDir: 'desc',
    titleKey: 'degree',
    fields: [
      { key: 'institution', label: 'Institution', type: 'text', required: true },
      { key: 'degree', label: 'Degree', type: 'text', required: true },
      { key: 'field', label: 'Field of Study', type: 'text' },
      { key: 'start', label: 'Start Year', type: 'text', required: true, placeholder: 'e.g. 2021' },
      { key: 'end', label: 'End Year', type: 'text', placeholder: 'e.g. 2025 or Present' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  skills: {
    collection: 'skills',
    label: 'Skills',
    singular: 'Skill',
    orderField: 'createdAt',
    orderDir: 'desc',
    titleKey: 'name',
    fields: [
      { key: 'name', label: 'Skill Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text', placeholder: 'e.g. Machine Learning, Programming, Tools' },
      { key: 'level', label: 'Proficiency (0-100)', type: 'number', min: 0, max: 100 },
    ],
  },
  projects: {
    collection: 'projects',
    label: 'Projects',
    singular: 'Project',
    orderField: 'createdAt',
    orderDir: 'desc',
    titleKey: 'title',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'tech', label: 'Tech Stack (comma separated)', type: 'list' },
      { key: 'github', label: 'GitHub URL', type: 'text' },
      { key: 'demo', label: 'Live Demo URL', type: 'text' },
      { key: 'image', label: 'Image URL', type: 'text' },
    ],
  },
  patents: {
    collection: 'patents',
    label: 'Patents',
    singular: 'Patent',
    orderField: 'createdAt',
    orderDir: 'desc',
    titleKey: 'title',
    fields: [
      { key: 'title', label: 'Patent Title', type: 'text', required: true },
      { key: 'patentNumber', label: 'Patent / Application Number', type: 'text' },
      { key: 'status', label: 'Status', type: 'text', placeholder: 'e.g. Filed, Published, Granted' },
      { key: 'year', label: 'Year', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  papers: {
    collection: 'papers',
    label: 'Research Papers',
    singular: 'Paper',
    orderField: 'year',
    orderDir: 'desc',
    titleKey: 'title',
    fields: [
      { key: 'title', label: 'Paper Title', type: 'text', required: true },
      { key: 'authors', label: 'Authors', type: 'text', placeholder: 'e.g. You, Co-author' },
      { key: 'journal', label: 'Journal / Conference', type: 'text' },
      { key: 'year', label: 'Year', type: 'text', required: true },
      { key: 'link', label: 'Paper URL', type: 'text' },
      { key: 'description', label: 'Abstract / Summary', type: 'textarea' },
    ],
  },
  certifications: {
    collection: 'certifications',
    label: 'Certifications',
    singular: 'Certification',
    orderField: 'createdAt',
    orderDir: 'desc',
    titleKey: 'title',
    fields: [
      { key: 'title', label: 'Certification Title', type: 'text', required: true },
      { key: 'issuer', label: 'Issued By', type: 'text' },
      { key: 'year', label: 'Year', type: 'text' },
      { key: 'credentialUrl', label: 'Credential URL', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  achievements: {
    collection: 'achievements',
    label: 'Achievements',
    singular: 'Achievement',
    orderField: 'createdAt',
    orderDir: 'desc',
    titleKey: 'title',
    fields: [
      { key: 'title', label: 'Achievement Title', type: 'text', required: true },
      { key: 'year', label: 'Year', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  blog: {
    collection: 'blog',
    label: 'Blog Posts',
    singular: 'Blog Post',
    orderField: 'createdAt',
    orderDir: 'desc',
    titleKey: 'title',
    fields: [
      { key: 'title', label: 'Post Title', type: 'text', required: true },
      { key: 'tags', label: 'Tags (comma separated)', type: 'list' },
      { key: 'coverImage', label: 'Cover Image URL', type: 'text' },
      { key: 'content', label: 'Content (blank line between paragraphs)', type: 'textarea', rows: 12 },
      { key: 'published', label: 'Published (visible to everyone)', type: 'boolean' },
    ],
  },
};

export const PROFILE_FIELDS = [
  { key: 'name', label: 'Full Name' },
  { key: 'title', label: 'Professional Title', placeholder: 'e.g. AI / ML Engineer' },
  { key: 'tagline', label: 'Tagline', placeholder: 'One line about what you do' },
  { key: 'bio', label: 'Bio', type: 'textarea', rows: 5 },
  { key: 'email', label: 'Email' },
  { key: 'location', label: 'Location' },
  { key: 'university', label: 'University / College' },
  { key: 'resumeUrl', label: 'Resume / CV URL' },
  { key: 'avatarUrl', label: 'Avatar Image URL' },
];

export const SOCIAL_FIELDS = [
  { key: 'github', label: 'GitHub' },
  { key: 'linkedin', label: 'LinkedIn' },
  { key: 'leetcode', label: 'LeetCode' },
  { key: 'twitter', label: 'Twitter / X' },
  { key: 'instagram', label: 'Instagram' },
  { key: 'telegram', label: 'Telegram' },
  { key: 'website', label: 'Website' },
];
